packages:
  # Include all of the core configuration
  core: !include freezermonitor.yaml

esphome:
  # This will allow for project identification,
  # configuration and updates.
  project:
    name: delqueso.freezermonitor
    version: dev # This will be replaced by the github workflows with the `release` version

# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
improv_serial:

